spring:
    cloud:
       consul:
           host: localhost
           port: 8500
           discovery:
              healthCheckPath: /health
              healthCheckInterval: 15s
              instance-id: consuls
              enabled: true
           enabled: true
    application:
      name: consul2
